changesetBaseRefs:
  - dev
  - origin/dev
  - upstream/dev

changesetIgnorePatterns:
  - .yarn/cache/**
  - .trunk/**
  - .husky/**
  - "**/coverage/**"
  - "**/.eslint*"
  - "**/.prettier*"
  - "**/.vscode/**"
  - "**/.markdownlint.*"
  - "**/.shellcheckrc"
  - "**/jest.config.*"

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
